name: Deploy

on:
  push:
    branches:
      - production

defaults:
  run:
    working-directory: 'Call of Anoro€'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - run: chmod u+x ./gradlew
      - run: ./gradlew server:assembleShadowDist 
      - run: cp Procfile server/build/libs
      - uses: akhileshns/heroku-deploy@v3.3.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "call-of-anoroc" #Must be unique in Heroku
          heroku_email: "ilyamerzlakov@gmail.com" 
          appdir: "Call of Anoro€/server/build/libs"